//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiDriverSystem.SQLWebServiceReference4 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SQLWebServiceReference4.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        TaxiDriverSystem.SQLWebServiceReference4.HelloWorldResponse HelloWorld(TaxiDriverSystem.SQLWebServiceReference4.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference4.HelloWorldResponse> HelloWorldAsync(TaxiDriverSystem.SQLWebServiceReference4.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name date from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertStartDay", ReplyAction="*")]
        TaxiDriverSystem.SQLWebServiceReference4.InsertStartDayResponse InsertStartDay(TaxiDriverSystem.SQLWebServiceReference4.InsertStartDayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertStartDay", ReplyAction="*")]
        System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference4.InsertStartDayResponse> InsertStartDayAsync(TaxiDriverSystem.SQLWebServiceReference4.InsertStartDayRequest request);
        
        // CODEGEN: Generating message contract since element name date from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertEndDay", ReplyAction="*")]
        TaxiDriverSystem.SQLWebServiceReference4.InsertEndDayResponse InsertEndDay(TaxiDriverSystem.SQLWebServiceReference4.InsertEndDayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertEndDay", ReplyAction="*")]
        System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference4.InsertEndDayResponse> InsertEndDayAsync(TaxiDriverSystem.SQLWebServiceReference4.InsertEndDayRequest request);
        
        // CODEGEN: Generating message contract since element name date from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertJourneyStart", ReplyAction="*")]
        TaxiDriverSystem.SQLWebServiceReference4.InsertJourneyStartResponse InsertJourneyStart(TaxiDriverSystem.SQLWebServiceReference4.InsertJourneyStartRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertJourneyStart", ReplyAction="*")]
        System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference4.InsertJourneyStartResponse> InsertJourneyStartAsync(TaxiDriverSystem.SQLWebServiceReference4.InsertJourneyStartRequest request);
        
        // CODEGEN: Generating message contract since element name date from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertJourneyEnd", ReplyAction="*")]
        TaxiDriverSystem.SQLWebServiceReference4.InsertJourneyEndResponse InsertJourneyEnd(TaxiDriverSystem.SQLWebServiceReference4.InsertJourneyEndRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertJourneyEnd", ReplyAction="*")]
        System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference4.InsertJourneyEndResponse> InsertJourneyEndAsync(TaxiDriverSystem.SQLWebServiceReference4.InsertJourneyEndRequest request);
        
        // CODEGEN: Generating message contract since element name date from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JourneyID", ReplyAction="*")]
        TaxiDriverSystem.SQLWebServiceReference4.JourneyIDResponse JourneyID(TaxiDriverSystem.SQLWebServiceReference4.JourneyIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JourneyID", ReplyAction="*")]
        System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference4.JourneyIDResponse> JourneyIDAsync(TaxiDriverSystem.SQLWebServiceReference4.JourneyIDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public TaxiDriverSystem.SQLWebServiceReference4.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(TaxiDriverSystem.SQLWebServiceReference4.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaxiDriverSystem.SQLWebServiceReference4.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(TaxiDriverSystem.SQLWebServiceReference4.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertStartDayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertStartDay", Namespace="http://tempuri.org/", Order=0)]
        public TaxiDriverSystem.SQLWebServiceReference4.InsertStartDayRequestBody Body;
        
        public InsertStartDayRequest() {
        }
        
        public InsertStartDayRequest(TaxiDriverSystem.SQLWebServiceReference4.InsertStartDayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertStartDayRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int DID;
        
        public InsertStartDayRequestBody() {
        }
        
        public InsertStartDayRequestBody(string date, int DID) {
            this.date = date;
            this.DID = DID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertStartDayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertStartDayResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaxiDriverSystem.SQLWebServiceReference4.InsertStartDayResponseBody Body;
        
        public InsertStartDayResponse() {
        }
        
        public InsertStartDayResponse(TaxiDriverSystem.SQLWebServiceReference4.InsertStartDayResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertStartDayResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertStartDayResult;
        
        public InsertStartDayResponseBody() {
        }
        
        public InsertStartDayResponseBody(string InsertStartDayResult) {
            this.InsertStartDayResult = InsertStartDayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertEndDayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertEndDay", Namespace="http://tempuri.org/", Order=0)]
        public TaxiDriverSystem.SQLWebServiceReference4.InsertEndDayRequestBody Body;
        
        public InsertEndDayRequest() {
        }
        
        public InsertEndDayRequest(TaxiDriverSystem.SQLWebServiceReference4.InsertEndDayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertEndDayRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int DID;
        
        public InsertEndDayRequestBody() {
        }
        
        public InsertEndDayRequestBody(string date, int DID) {
            this.date = date;
            this.DID = DID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertEndDayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertEndDayResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaxiDriverSystem.SQLWebServiceReference4.InsertEndDayResponseBody Body;
        
        public InsertEndDayResponse() {
        }
        
        public InsertEndDayResponse(TaxiDriverSystem.SQLWebServiceReference4.InsertEndDayResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertEndDayResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertEndDayResult;
        
        public InsertEndDayResponseBody() {
        }
        
        public InsertEndDayResponseBody(string InsertEndDayResult) {
            this.InsertEndDayResult = InsertEndDayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertJourneyStartRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertJourneyStart", Namespace="http://tempuri.org/", Order=0)]
        public TaxiDriverSystem.SQLWebServiceReference4.InsertJourneyStartRequestBody Body;
        
        public InsertJourneyStartRequest() {
        }
        
        public InsertJourneyStartRequest(TaxiDriverSystem.SQLWebServiceReference4.InsertJourneyStartRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertJourneyStartRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int DID;
        
        public InsertJourneyStartRequestBody() {
        }
        
        public InsertJourneyStartRequestBody(string date, int DID) {
            this.date = date;
            this.DID = DID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertJourneyStartResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertJourneyStartResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaxiDriverSystem.SQLWebServiceReference4.InsertJourneyStartResponseBody Body;
        
        public InsertJourneyStartResponse() {
        }
        
        public InsertJourneyStartResponse(TaxiDriverSystem.SQLWebServiceReference4.InsertJourneyStartResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertJourneyStartResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertJourneyStartResult;
        
        public InsertJourneyStartResponseBody() {
        }
        
        public InsertJourneyStartResponseBody(string InsertJourneyStartResult) {
            this.InsertJourneyStartResult = InsertJourneyStartResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertJourneyEndRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertJourneyEnd", Namespace="http://tempuri.org/", Order=0)]
        public TaxiDriverSystem.SQLWebServiceReference4.InsertJourneyEndRequestBody Body;
        
        public InsertJourneyEndRequest() {
        }
        
        public InsertJourneyEndRequest(TaxiDriverSystem.SQLWebServiceReference4.InsertJourneyEndRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertJourneyEndRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int DID;
        
        public InsertJourneyEndRequestBody() {
        }
        
        public InsertJourneyEndRequestBody(string date, int DID) {
            this.date = date;
            this.DID = DID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertJourneyEndResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertJourneyEndResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaxiDriverSystem.SQLWebServiceReference4.InsertJourneyEndResponseBody Body;
        
        public InsertJourneyEndResponse() {
        }
        
        public InsertJourneyEndResponse(TaxiDriverSystem.SQLWebServiceReference4.InsertJourneyEndResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertJourneyEndResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertJourneyEndResult;
        
        public InsertJourneyEndResponseBody() {
        }
        
        public InsertJourneyEndResponseBody(string InsertJourneyEndResult) {
            this.InsertJourneyEndResult = InsertJourneyEndResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JourneyIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JourneyID", Namespace="http://tempuri.org/", Order=0)]
        public TaxiDriverSystem.SQLWebServiceReference4.JourneyIDRequestBody Body;
        
        public JourneyIDRequest() {
        }
        
        public JourneyIDRequest(TaxiDriverSystem.SQLWebServiceReference4.JourneyIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class JourneyIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int D_ID;
        
        public JourneyIDRequestBody() {
        }
        
        public JourneyIDRequestBody(string date, int D_ID) {
            this.date = date;
            this.D_ID = D_ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JourneyIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JourneyIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaxiDriverSystem.SQLWebServiceReference4.JourneyIDResponseBody Body;
        
        public JourneyIDResponse() {
        }
        
        public JourneyIDResponse(TaxiDriverSystem.SQLWebServiceReference4.JourneyIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class JourneyIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int JourneyIDResult;
        
        public JourneyIDResponseBody() {
        }
        
        public JourneyIDResponseBody(int JourneyIDResult) {
            this.JourneyIDResult = JourneyIDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : TaxiDriverSystem.SQLWebServiceReference4.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<TaxiDriverSystem.SQLWebServiceReference4.WebService1Soap>, TaxiDriverSystem.SQLWebServiceReference4.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaxiDriverSystem.SQLWebServiceReference4.HelloWorldResponse TaxiDriverSystem.SQLWebServiceReference4.WebService1Soap.HelloWorld(TaxiDriverSystem.SQLWebServiceReference4.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            TaxiDriverSystem.SQLWebServiceReference4.HelloWorldRequest inValue = new TaxiDriverSystem.SQLWebServiceReference4.HelloWorldRequest();
            inValue.Body = new TaxiDriverSystem.SQLWebServiceReference4.HelloWorldRequestBody();
            TaxiDriverSystem.SQLWebServiceReference4.HelloWorldResponse retVal = ((TaxiDriverSystem.SQLWebServiceReference4.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference4.HelloWorldResponse> TaxiDriverSystem.SQLWebServiceReference4.WebService1Soap.HelloWorldAsync(TaxiDriverSystem.SQLWebServiceReference4.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference4.HelloWorldResponse> HelloWorldAsync() {
            TaxiDriverSystem.SQLWebServiceReference4.HelloWorldRequest inValue = new TaxiDriverSystem.SQLWebServiceReference4.HelloWorldRequest();
            inValue.Body = new TaxiDriverSystem.SQLWebServiceReference4.HelloWorldRequestBody();
            return ((TaxiDriverSystem.SQLWebServiceReference4.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaxiDriverSystem.SQLWebServiceReference4.InsertStartDayResponse TaxiDriverSystem.SQLWebServiceReference4.WebService1Soap.InsertStartDay(TaxiDriverSystem.SQLWebServiceReference4.InsertStartDayRequest request) {
            return base.Channel.InsertStartDay(request);
        }
        
        public string InsertStartDay(string date, int DID) {
            TaxiDriverSystem.SQLWebServiceReference4.InsertStartDayRequest inValue = new TaxiDriverSystem.SQLWebServiceReference4.InsertStartDayRequest();
            inValue.Body = new TaxiDriverSystem.SQLWebServiceReference4.InsertStartDayRequestBody();
            inValue.Body.date = date;
            inValue.Body.DID = DID;
            TaxiDriverSystem.SQLWebServiceReference4.InsertStartDayResponse retVal = ((TaxiDriverSystem.SQLWebServiceReference4.WebService1Soap)(this)).InsertStartDay(inValue);
            return retVal.Body.InsertStartDayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference4.InsertStartDayResponse> TaxiDriverSystem.SQLWebServiceReference4.WebService1Soap.InsertStartDayAsync(TaxiDriverSystem.SQLWebServiceReference4.InsertStartDayRequest request) {
            return base.Channel.InsertStartDayAsync(request);
        }
        
        public System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference4.InsertStartDayResponse> InsertStartDayAsync(string date, int DID) {
            TaxiDriverSystem.SQLWebServiceReference4.InsertStartDayRequest inValue = new TaxiDriverSystem.SQLWebServiceReference4.InsertStartDayRequest();
            inValue.Body = new TaxiDriverSystem.SQLWebServiceReference4.InsertStartDayRequestBody();
            inValue.Body.date = date;
            inValue.Body.DID = DID;
            return ((TaxiDriverSystem.SQLWebServiceReference4.WebService1Soap)(this)).InsertStartDayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaxiDriverSystem.SQLWebServiceReference4.InsertEndDayResponse TaxiDriverSystem.SQLWebServiceReference4.WebService1Soap.InsertEndDay(TaxiDriverSystem.SQLWebServiceReference4.InsertEndDayRequest request) {
            return base.Channel.InsertEndDay(request);
        }
        
        public string InsertEndDay(string date, int DID) {
            TaxiDriverSystem.SQLWebServiceReference4.InsertEndDayRequest inValue = new TaxiDriverSystem.SQLWebServiceReference4.InsertEndDayRequest();
            inValue.Body = new TaxiDriverSystem.SQLWebServiceReference4.InsertEndDayRequestBody();
            inValue.Body.date = date;
            inValue.Body.DID = DID;
            TaxiDriverSystem.SQLWebServiceReference4.InsertEndDayResponse retVal = ((TaxiDriverSystem.SQLWebServiceReference4.WebService1Soap)(this)).InsertEndDay(inValue);
            return retVal.Body.InsertEndDayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference4.InsertEndDayResponse> TaxiDriverSystem.SQLWebServiceReference4.WebService1Soap.InsertEndDayAsync(TaxiDriverSystem.SQLWebServiceReference4.InsertEndDayRequest request) {
            return base.Channel.InsertEndDayAsync(request);
        }
        
        public System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference4.InsertEndDayResponse> InsertEndDayAsync(string date, int DID) {
            TaxiDriverSystem.SQLWebServiceReference4.InsertEndDayRequest inValue = new TaxiDriverSystem.SQLWebServiceReference4.InsertEndDayRequest();
            inValue.Body = new TaxiDriverSystem.SQLWebServiceReference4.InsertEndDayRequestBody();
            inValue.Body.date = date;
            inValue.Body.DID = DID;
            return ((TaxiDriverSystem.SQLWebServiceReference4.WebService1Soap)(this)).InsertEndDayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaxiDriverSystem.SQLWebServiceReference4.InsertJourneyStartResponse TaxiDriverSystem.SQLWebServiceReference4.WebService1Soap.InsertJourneyStart(TaxiDriverSystem.SQLWebServiceReference4.InsertJourneyStartRequest request) {
            return base.Channel.InsertJourneyStart(request);
        }
        
        public string InsertJourneyStart(string date, int DID) {
            TaxiDriverSystem.SQLWebServiceReference4.InsertJourneyStartRequest inValue = new TaxiDriverSystem.SQLWebServiceReference4.InsertJourneyStartRequest();
            inValue.Body = new TaxiDriverSystem.SQLWebServiceReference4.InsertJourneyStartRequestBody();
            inValue.Body.date = date;
            inValue.Body.DID = DID;
            TaxiDriverSystem.SQLWebServiceReference4.InsertJourneyStartResponse retVal = ((TaxiDriverSystem.SQLWebServiceReference4.WebService1Soap)(this)).InsertJourneyStart(inValue);
            return retVal.Body.InsertJourneyStartResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference4.InsertJourneyStartResponse> TaxiDriverSystem.SQLWebServiceReference4.WebService1Soap.InsertJourneyStartAsync(TaxiDriverSystem.SQLWebServiceReference4.InsertJourneyStartRequest request) {
            return base.Channel.InsertJourneyStartAsync(request);
        }
        
        public System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference4.InsertJourneyStartResponse> InsertJourneyStartAsync(string date, int DID) {
            TaxiDriverSystem.SQLWebServiceReference4.InsertJourneyStartRequest inValue = new TaxiDriverSystem.SQLWebServiceReference4.InsertJourneyStartRequest();
            inValue.Body = new TaxiDriverSystem.SQLWebServiceReference4.InsertJourneyStartRequestBody();
            inValue.Body.date = date;
            inValue.Body.DID = DID;
            return ((TaxiDriverSystem.SQLWebServiceReference4.WebService1Soap)(this)).InsertJourneyStartAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaxiDriverSystem.SQLWebServiceReference4.InsertJourneyEndResponse TaxiDriverSystem.SQLWebServiceReference4.WebService1Soap.InsertJourneyEnd(TaxiDriverSystem.SQLWebServiceReference4.InsertJourneyEndRequest request) {
            return base.Channel.InsertJourneyEnd(request);
        }
        
        public string InsertJourneyEnd(string date, int DID) {
            TaxiDriverSystem.SQLWebServiceReference4.InsertJourneyEndRequest inValue = new TaxiDriverSystem.SQLWebServiceReference4.InsertJourneyEndRequest();
            inValue.Body = new TaxiDriverSystem.SQLWebServiceReference4.InsertJourneyEndRequestBody();
            inValue.Body.date = date;
            inValue.Body.DID = DID;
            TaxiDriverSystem.SQLWebServiceReference4.InsertJourneyEndResponse retVal = ((TaxiDriverSystem.SQLWebServiceReference4.WebService1Soap)(this)).InsertJourneyEnd(inValue);
            return retVal.Body.InsertJourneyEndResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference4.InsertJourneyEndResponse> TaxiDriverSystem.SQLWebServiceReference4.WebService1Soap.InsertJourneyEndAsync(TaxiDriverSystem.SQLWebServiceReference4.InsertJourneyEndRequest request) {
            return base.Channel.InsertJourneyEndAsync(request);
        }
        
        public System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference4.InsertJourneyEndResponse> InsertJourneyEndAsync(string date, int DID) {
            TaxiDriverSystem.SQLWebServiceReference4.InsertJourneyEndRequest inValue = new TaxiDriverSystem.SQLWebServiceReference4.InsertJourneyEndRequest();
            inValue.Body = new TaxiDriverSystem.SQLWebServiceReference4.InsertJourneyEndRequestBody();
            inValue.Body.date = date;
            inValue.Body.DID = DID;
            return ((TaxiDriverSystem.SQLWebServiceReference4.WebService1Soap)(this)).InsertJourneyEndAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaxiDriverSystem.SQLWebServiceReference4.JourneyIDResponse TaxiDriverSystem.SQLWebServiceReference4.WebService1Soap.JourneyID(TaxiDriverSystem.SQLWebServiceReference4.JourneyIDRequest request) {
            return base.Channel.JourneyID(request);
        }
        
        public int JourneyID(string date, int D_ID) {
            TaxiDriverSystem.SQLWebServiceReference4.JourneyIDRequest inValue = new TaxiDriverSystem.SQLWebServiceReference4.JourneyIDRequest();
            inValue.Body = new TaxiDriverSystem.SQLWebServiceReference4.JourneyIDRequestBody();
            inValue.Body.date = date;
            inValue.Body.D_ID = D_ID;
            TaxiDriverSystem.SQLWebServiceReference4.JourneyIDResponse retVal = ((TaxiDriverSystem.SQLWebServiceReference4.WebService1Soap)(this)).JourneyID(inValue);
            return retVal.Body.JourneyIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference4.JourneyIDResponse> TaxiDriverSystem.SQLWebServiceReference4.WebService1Soap.JourneyIDAsync(TaxiDriverSystem.SQLWebServiceReference4.JourneyIDRequest request) {
            return base.Channel.JourneyIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference4.JourneyIDResponse> JourneyIDAsync(string date, int D_ID) {
            TaxiDriverSystem.SQLWebServiceReference4.JourneyIDRequest inValue = new TaxiDriverSystem.SQLWebServiceReference4.JourneyIDRequest();
            inValue.Body = new TaxiDriverSystem.SQLWebServiceReference4.JourneyIDRequestBody();
            inValue.Body.date = date;
            inValue.Body.D_ID = D_ID;
            return ((TaxiDriverSystem.SQLWebServiceReference4.WebService1Soap)(this)).JourneyIDAsync(inValue);
        }
    }
}
