//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiDriverSystem.SQLWebServiceReference3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SQLWebServiceReference3.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        TaxiDriverSystem.SQLWebServiceReference3.HelloWorldResponse HelloWorld(TaxiDriverSystem.SQLWebServiceReference3.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference3.HelloWorldResponse> HelloWorldAsync(TaxiDriverSystem.SQLWebServiceReference3.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name date from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertStartDay", ReplyAction="*")]
        TaxiDriverSystem.SQLWebServiceReference3.InsertStartDayResponse InsertStartDay(TaxiDriverSystem.SQLWebServiceReference3.InsertStartDayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertStartDay", ReplyAction="*")]
        System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference3.InsertStartDayResponse> InsertStartDayAsync(TaxiDriverSystem.SQLWebServiceReference3.InsertStartDayRequest request);
        
        // CODEGEN: Generating message contract since element name date from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertEndDay", ReplyAction="*")]
        TaxiDriverSystem.SQLWebServiceReference3.InsertEndDayResponse InsertEndDay(TaxiDriverSystem.SQLWebServiceReference3.InsertEndDayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertEndDay", ReplyAction="*")]
        System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference3.InsertEndDayResponse> InsertEndDayAsync(TaxiDriverSystem.SQLWebServiceReference3.InsertEndDayRequest request);
        
        // CODEGEN: Generating message contract since element name date from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertJourneyStart", ReplyAction="*")]
        TaxiDriverSystem.SQLWebServiceReference3.InsertJourneyStartResponse InsertJourneyStart(TaxiDriverSystem.SQLWebServiceReference3.InsertJourneyStartRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertJourneyStart", ReplyAction="*")]
        System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference3.InsertJourneyStartResponse> InsertJourneyStartAsync(TaxiDriverSystem.SQLWebServiceReference3.InsertJourneyStartRequest request);
        
        // CODEGEN: Generating message contract since element name date from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertJourneyEnd", ReplyAction="*")]
        TaxiDriverSystem.SQLWebServiceReference3.InsertJourneyEndResponse InsertJourneyEnd(TaxiDriverSystem.SQLWebServiceReference3.InsertJourneyEndRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertJourneyEnd", ReplyAction="*")]
        System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference3.InsertJourneyEndResponse> InsertJourneyEndAsync(TaxiDriverSystem.SQLWebServiceReference3.InsertJourneyEndRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public TaxiDriverSystem.SQLWebServiceReference3.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(TaxiDriverSystem.SQLWebServiceReference3.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaxiDriverSystem.SQLWebServiceReference3.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(TaxiDriverSystem.SQLWebServiceReference3.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertStartDayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertStartDay", Namespace="http://tempuri.org/", Order=0)]
        public TaxiDriverSystem.SQLWebServiceReference3.InsertStartDayRequestBody Body;
        
        public InsertStartDayRequest() {
        }
        
        public InsertStartDayRequest(TaxiDriverSystem.SQLWebServiceReference3.InsertStartDayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertStartDayRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int DID;
        
        public InsertStartDayRequestBody() {
        }
        
        public InsertStartDayRequestBody(string date, int DID) {
            this.date = date;
            this.DID = DID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertStartDayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertStartDayResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaxiDriverSystem.SQLWebServiceReference3.InsertStartDayResponseBody Body;
        
        public InsertStartDayResponse() {
        }
        
        public InsertStartDayResponse(TaxiDriverSystem.SQLWebServiceReference3.InsertStartDayResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertStartDayResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertStartDayResult;
        
        public InsertStartDayResponseBody() {
        }
        
        public InsertStartDayResponseBody(string InsertStartDayResult) {
            this.InsertStartDayResult = InsertStartDayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertEndDayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertEndDay", Namespace="http://tempuri.org/", Order=0)]
        public TaxiDriverSystem.SQLWebServiceReference3.InsertEndDayRequestBody Body;
        
        public InsertEndDayRequest() {
        }
        
        public InsertEndDayRequest(TaxiDriverSystem.SQLWebServiceReference3.InsertEndDayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertEndDayRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int DID;
        
        public InsertEndDayRequestBody() {
        }
        
        public InsertEndDayRequestBody(string date, int DID) {
            this.date = date;
            this.DID = DID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertEndDayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertEndDayResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaxiDriverSystem.SQLWebServiceReference3.InsertEndDayResponseBody Body;
        
        public InsertEndDayResponse() {
        }
        
        public InsertEndDayResponse(TaxiDriverSystem.SQLWebServiceReference3.InsertEndDayResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertEndDayResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertEndDayResult;
        
        public InsertEndDayResponseBody() {
        }
        
        public InsertEndDayResponseBody(string InsertEndDayResult) {
            this.InsertEndDayResult = InsertEndDayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertJourneyStartRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertJourneyStart", Namespace="http://tempuri.org/", Order=0)]
        public TaxiDriverSystem.SQLWebServiceReference3.InsertJourneyStartRequestBody Body;
        
        public InsertJourneyStartRequest() {
        }
        
        public InsertJourneyStartRequest(TaxiDriverSystem.SQLWebServiceReference3.InsertJourneyStartRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertJourneyStartRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int DID;
        
        public InsertJourneyStartRequestBody() {
        }
        
        public InsertJourneyStartRequestBody(string date, int DID) {
            this.date = date;
            this.DID = DID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertJourneyStartResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertJourneyStartResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaxiDriverSystem.SQLWebServiceReference3.InsertJourneyStartResponseBody Body;
        
        public InsertJourneyStartResponse() {
        }
        
        public InsertJourneyStartResponse(TaxiDriverSystem.SQLWebServiceReference3.InsertJourneyStartResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertJourneyStartResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertJourneyStartResult;
        
        public InsertJourneyStartResponseBody() {
        }
        
        public InsertJourneyStartResponseBody(string InsertJourneyStartResult) {
            this.InsertJourneyStartResult = InsertJourneyStartResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertJourneyEndRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertJourneyEnd", Namespace="http://tempuri.org/", Order=0)]
        public TaxiDriverSystem.SQLWebServiceReference3.InsertJourneyEndRequestBody Body;
        
        public InsertJourneyEndRequest() {
        }
        
        public InsertJourneyEndRequest(TaxiDriverSystem.SQLWebServiceReference3.InsertJourneyEndRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertJourneyEndRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int DID;
        
        public InsertJourneyEndRequestBody() {
        }
        
        public InsertJourneyEndRequestBody(string date, int DID) {
            this.date = date;
            this.DID = DID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertJourneyEndResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertJourneyEndResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaxiDriverSystem.SQLWebServiceReference3.InsertJourneyEndResponseBody Body;
        
        public InsertJourneyEndResponse() {
        }
        
        public InsertJourneyEndResponse(TaxiDriverSystem.SQLWebServiceReference3.InsertJourneyEndResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertJourneyEndResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertJourneyEndResult;
        
        public InsertJourneyEndResponseBody() {
        }
        
        public InsertJourneyEndResponseBody(string InsertJourneyEndResult) {
            this.InsertJourneyEndResult = InsertJourneyEndResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : TaxiDriverSystem.SQLWebServiceReference3.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<TaxiDriverSystem.SQLWebServiceReference3.WebService1Soap>, TaxiDriverSystem.SQLWebServiceReference3.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaxiDriverSystem.SQLWebServiceReference3.HelloWorldResponse TaxiDriverSystem.SQLWebServiceReference3.WebService1Soap.HelloWorld(TaxiDriverSystem.SQLWebServiceReference3.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            TaxiDriverSystem.SQLWebServiceReference3.HelloWorldRequest inValue = new TaxiDriverSystem.SQLWebServiceReference3.HelloWorldRequest();
            inValue.Body = new TaxiDriverSystem.SQLWebServiceReference3.HelloWorldRequestBody();
            TaxiDriverSystem.SQLWebServiceReference3.HelloWorldResponse retVal = ((TaxiDriverSystem.SQLWebServiceReference3.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference3.HelloWorldResponse> TaxiDriverSystem.SQLWebServiceReference3.WebService1Soap.HelloWorldAsync(TaxiDriverSystem.SQLWebServiceReference3.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference3.HelloWorldResponse> HelloWorldAsync() {
            TaxiDriverSystem.SQLWebServiceReference3.HelloWorldRequest inValue = new TaxiDriverSystem.SQLWebServiceReference3.HelloWorldRequest();
            inValue.Body = new TaxiDriverSystem.SQLWebServiceReference3.HelloWorldRequestBody();
            return ((TaxiDriverSystem.SQLWebServiceReference3.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaxiDriverSystem.SQLWebServiceReference3.InsertStartDayResponse TaxiDriverSystem.SQLWebServiceReference3.WebService1Soap.InsertStartDay(TaxiDriverSystem.SQLWebServiceReference3.InsertStartDayRequest request) {
            return base.Channel.InsertStartDay(request);
        }
        
        public string InsertStartDay(string date, int DID) {
            TaxiDriverSystem.SQLWebServiceReference3.InsertStartDayRequest inValue = new TaxiDriverSystem.SQLWebServiceReference3.InsertStartDayRequest();
            inValue.Body = new TaxiDriverSystem.SQLWebServiceReference3.InsertStartDayRequestBody();
            inValue.Body.date = date;
            inValue.Body.DID = DID;
            TaxiDriverSystem.SQLWebServiceReference3.InsertStartDayResponse retVal = ((TaxiDriverSystem.SQLWebServiceReference3.WebService1Soap)(this)).InsertStartDay(inValue);
            return retVal.Body.InsertStartDayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference3.InsertStartDayResponse> TaxiDriverSystem.SQLWebServiceReference3.WebService1Soap.InsertStartDayAsync(TaxiDriverSystem.SQLWebServiceReference3.InsertStartDayRequest request) {
            return base.Channel.InsertStartDayAsync(request);
        }
        
        public System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference3.InsertStartDayResponse> InsertStartDayAsync(string date, int DID) {
            TaxiDriverSystem.SQLWebServiceReference3.InsertStartDayRequest inValue = new TaxiDriverSystem.SQLWebServiceReference3.InsertStartDayRequest();
            inValue.Body = new TaxiDriverSystem.SQLWebServiceReference3.InsertStartDayRequestBody();
            inValue.Body.date = date;
            inValue.Body.DID = DID;
            return ((TaxiDriverSystem.SQLWebServiceReference3.WebService1Soap)(this)).InsertStartDayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaxiDriverSystem.SQLWebServiceReference3.InsertEndDayResponse TaxiDriverSystem.SQLWebServiceReference3.WebService1Soap.InsertEndDay(TaxiDriverSystem.SQLWebServiceReference3.InsertEndDayRequest request) {
            return base.Channel.InsertEndDay(request);
        }
        
        public string InsertEndDay(string date, int DID) {
            TaxiDriverSystem.SQLWebServiceReference3.InsertEndDayRequest inValue = new TaxiDriverSystem.SQLWebServiceReference3.InsertEndDayRequest();
            inValue.Body = new TaxiDriverSystem.SQLWebServiceReference3.InsertEndDayRequestBody();
            inValue.Body.date = date;
            inValue.Body.DID = DID;
            TaxiDriverSystem.SQLWebServiceReference3.InsertEndDayResponse retVal = ((TaxiDriverSystem.SQLWebServiceReference3.WebService1Soap)(this)).InsertEndDay(inValue);
            return retVal.Body.InsertEndDayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference3.InsertEndDayResponse> TaxiDriverSystem.SQLWebServiceReference3.WebService1Soap.InsertEndDayAsync(TaxiDriverSystem.SQLWebServiceReference3.InsertEndDayRequest request) {
            return base.Channel.InsertEndDayAsync(request);
        }
        
        public System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference3.InsertEndDayResponse> InsertEndDayAsync(string date, int DID) {
            TaxiDriverSystem.SQLWebServiceReference3.InsertEndDayRequest inValue = new TaxiDriverSystem.SQLWebServiceReference3.InsertEndDayRequest();
            inValue.Body = new TaxiDriverSystem.SQLWebServiceReference3.InsertEndDayRequestBody();
            inValue.Body.date = date;
            inValue.Body.DID = DID;
            return ((TaxiDriverSystem.SQLWebServiceReference3.WebService1Soap)(this)).InsertEndDayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaxiDriverSystem.SQLWebServiceReference3.InsertJourneyStartResponse TaxiDriverSystem.SQLWebServiceReference3.WebService1Soap.InsertJourneyStart(TaxiDriverSystem.SQLWebServiceReference3.InsertJourneyStartRequest request) {
            return base.Channel.InsertJourneyStart(request);
        }
        
        public string InsertJourneyStart(string date, int DID) {
            TaxiDriverSystem.SQLWebServiceReference3.InsertJourneyStartRequest inValue = new TaxiDriverSystem.SQLWebServiceReference3.InsertJourneyStartRequest();
            inValue.Body = new TaxiDriverSystem.SQLWebServiceReference3.InsertJourneyStartRequestBody();
            inValue.Body.date = date;
            inValue.Body.DID = DID;
            TaxiDriverSystem.SQLWebServiceReference3.InsertJourneyStartResponse retVal = ((TaxiDriverSystem.SQLWebServiceReference3.WebService1Soap)(this)).InsertJourneyStart(inValue);
            return retVal.Body.InsertJourneyStartResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference3.InsertJourneyStartResponse> TaxiDriverSystem.SQLWebServiceReference3.WebService1Soap.InsertJourneyStartAsync(TaxiDriverSystem.SQLWebServiceReference3.InsertJourneyStartRequest request) {
            return base.Channel.InsertJourneyStartAsync(request);
        }
        
        public System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference3.InsertJourneyStartResponse> InsertJourneyStartAsync(string date, int DID) {
            TaxiDriverSystem.SQLWebServiceReference3.InsertJourneyStartRequest inValue = new TaxiDriverSystem.SQLWebServiceReference3.InsertJourneyStartRequest();
            inValue.Body = new TaxiDriverSystem.SQLWebServiceReference3.InsertJourneyStartRequestBody();
            inValue.Body.date = date;
            inValue.Body.DID = DID;
            return ((TaxiDriverSystem.SQLWebServiceReference3.WebService1Soap)(this)).InsertJourneyStartAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaxiDriverSystem.SQLWebServiceReference3.InsertJourneyEndResponse TaxiDriverSystem.SQLWebServiceReference3.WebService1Soap.InsertJourneyEnd(TaxiDriverSystem.SQLWebServiceReference3.InsertJourneyEndRequest request) {
            return base.Channel.InsertJourneyEnd(request);
        }
        
        public string InsertJourneyEnd(string date, int DID) {
            TaxiDriverSystem.SQLWebServiceReference3.InsertJourneyEndRequest inValue = new TaxiDriverSystem.SQLWebServiceReference3.InsertJourneyEndRequest();
            inValue.Body = new TaxiDriverSystem.SQLWebServiceReference3.InsertJourneyEndRequestBody();
            inValue.Body.date = date;
            inValue.Body.DID = DID;
            TaxiDriverSystem.SQLWebServiceReference3.InsertJourneyEndResponse retVal = ((TaxiDriverSystem.SQLWebServiceReference3.WebService1Soap)(this)).InsertJourneyEnd(inValue);
            return retVal.Body.InsertJourneyEndResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference3.InsertJourneyEndResponse> TaxiDriverSystem.SQLWebServiceReference3.WebService1Soap.InsertJourneyEndAsync(TaxiDriverSystem.SQLWebServiceReference3.InsertJourneyEndRequest request) {
            return base.Channel.InsertJourneyEndAsync(request);
        }
        
        public System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference3.InsertJourneyEndResponse> InsertJourneyEndAsync(string date, int DID) {
            TaxiDriverSystem.SQLWebServiceReference3.InsertJourneyEndRequest inValue = new TaxiDriverSystem.SQLWebServiceReference3.InsertJourneyEndRequest();
            inValue.Body = new TaxiDriverSystem.SQLWebServiceReference3.InsertJourneyEndRequestBody();
            inValue.Body.date = date;
            inValue.Body.DID = DID;
            return ((TaxiDriverSystem.SQLWebServiceReference3.WebService1Soap)(this)).InsertJourneyEndAsync(inValue);
        }
    }
}
