//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiDriverSystem.SQLWebServiceReference5 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SQLWebServiceReference5.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        TaxiDriverSystem.SQLWebServiceReference5.HelloWorldResponse HelloWorld(TaxiDriverSystem.SQLWebServiceReference5.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference5.HelloWorldResponse> HelloWorldAsync(TaxiDriverSystem.SQLWebServiceReference5.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name date from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertStartDay", ReplyAction="*")]
        TaxiDriverSystem.SQLWebServiceReference5.InsertStartDayResponse InsertStartDay(TaxiDriverSystem.SQLWebServiceReference5.InsertStartDayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertStartDay", ReplyAction="*")]
        System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference5.InsertStartDayResponse> InsertStartDayAsync(TaxiDriverSystem.SQLWebServiceReference5.InsertStartDayRequest request);
        
        // CODEGEN: Generating message contract since element name date from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertEndDay", ReplyAction="*")]
        TaxiDriverSystem.SQLWebServiceReference5.InsertEndDayResponse InsertEndDay(TaxiDriverSystem.SQLWebServiceReference5.InsertEndDayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertEndDay", ReplyAction="*")]
        System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference5.InsertEndDayResponse> InsertEndDayAsync(TaxiDriverSystem.SQLWebServiceReference5.InsertEndDayRequest request);
        
        // CODEGEN: Generating message contract since element name date from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertJourneyStart", ReplyAction="*")]
        TaxiDriverSystem.SQLWebServiceReference5.InsertJourneyStartResponse InsertJourneyStart(TaxiDriverSystem.SQLWebServiceReference5.InsertJourneyStartRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertJourneyStart", ReplyAction="*")]
        System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference5.InsertJourneyStartResponse> InsertJourneyStartAsync(TaxiDriverSystem.SQLWebServiceReference5.InsertJourneyStartRequest request);
        
        // CODEGEN: Generating message contract since element name date from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertJourneyEnd", ReplyAction="*")]
        TaxiDriverSystem.SQLWebServiceReference5.InsertJourneyEndResponse InsertJourneyEnd(TaxiDriverSystem.SQLWebServiceReference5.InsertJourneyEndRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertJourneyEnd", ReplyAction="*")]
        System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference5.InsertJourneyEndResponse> InsertJourneyEndAsync(TaxiDriverSystem.SQLWebServiceReference5.InsertJourneyEndRequest request);
        
        // CODEGEN: Generating message contract since element name date from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JourneyID", ReplyAction="*")]
        TaxiDriverSystem.SQLWebServiceReference5.JourneyIDResponse JourneyID(TaxiDriverSystem.SQLWebServiceReference5.JourneyIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JourneyID", ReplyAction="*")]
        System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference5.JourneyIDResponse> JourneyIDAsync(TaxiDriverSystem.SQLWebServiceReference5.JourneyIDRequest request);
        
        // CODEGEN: Generating message contract since element name driverstartdaycheckResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/driverstartdaycheck", ReplyAction="*")]
        TaxiDriverSystem.SQLWebServiceReference5.driverstartdaycheckResponse driverstartdaycheck(TaxiDriverSystem.SQLWebServiceReference5.driverstartdaycheckRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/driverstartdaycheck", ReplyAction="*")]
        System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference5.driverstartdaycheckResponse> driverstartdaycheckAsync(TaxiDriverSystem.SQLWebServiceReference5.driverstartdaycheckRequest request);
        
        // CODEGEN: Generating message contract since element name Username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/driverLogin", ReplyAction="*")]
        TaxiDriverSystem.SQLWebServiceReference5.driverLoginResponse driverLogin(TaxiDriverSystem.SQLWebServiceReference5.driverLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/driverLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference5.driverLoginResponse> driverLoginAsync(TaxiDriverSystem.SQLWebServiceReference5.driverLoginRequest request);
        
        // CODEGEN: Generating message contract since element name Username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DriverID", ReplyAction="*")]
        TaxiDriverSystem.SQLWebServiceReference5.DriverIDResponse DriverID(TaxiDriverSystem.SQLWebServiceReference5.DriverIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DriverID", ReplyAction="*")]
        System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference5.DriverIDResponse> DriverIDAsync(TaxiDriverSystem.SQLWebServiceReference5.DriverIDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public TaxiDriverSystem.SQLWebServiceReference5.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(TaxiDriverSystem.SQLWebServiceReference5.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaxiDriverSystem.SQLWebServiceReference5.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(TaxiDriverSystem.SQLWebServiceReference5.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertStartDayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertStartDay", Namespace="http://tempuri.org/", Order=0)]
        public TaxiDriverSystem.SQLWebServiceReference5.InsertStartDayRequestBody Body;
        
        public InsertStartDayRequest() {
        }
        
        public InsertStartDayRequest(TaxiDriverSystem.SQLWebServiceReference5.InsertStartDayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertStartDayRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int DID;
        
        public InsertStartDayRequestBody() {
        }
        
        public InsertStartDayRequestBody(string date, int DID) {
            this.date = date;
            this.DID = DID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertStartDayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertStartDayResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaxiDriverSystem.SQLWebServiceReference5.InsertStartDayResponseBody Body;
        
        public InsertStartDayResponse() {
        }
        
        public InsertStartDayResponse(TaxiDriverSystem.SQLWebServiceReference5.InsertStartDayResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertStartDayResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertStartDayResult;
        
        public InsertStartDayResponseBody() {
        }
        
        public InsertStartDayResponseBody(string InsertStartDayResult) {
            this.InsertStartDayResult = InsertStartDayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertEndDayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertEndDay", Namespace="http://tempuri.org/", Order=0)]
        public TaxiDriverSystem.SQLWebServiceReference5.InsertEndDayRequestBody Body;
        
        public InsertEndDayRequest() {
        }
        
        public InsertEndDayRequest(TaxiDriverSystem.SQLWebServiceReference5.InsertEndDayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertEndDayRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int DID;
        
        public InsertEndDayRequestBody() {
        }
        
        public InsertEndDayRequestBody(string date, int DID) {
            this.date = date;
            this.DID = DID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertEndDayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertEndDayResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaxiDriverSystem.SQLWebServiceReference5.InsertEndDayResponseBody Body;
        
        public InsertEndDayResponse() {
        }
        
        public InsertEndDayResponse(TaxiDriverSystem.SQLWebServiceReference5.InsertEndDayResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertEndDayResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertEndDayResult;
        
        public InsertEndDayResponseBody() {
        }
        
        public InsertEndDayResponseBody(string InsertEndDayResult) {
            this.InsertEndDayResult = InsertEndDayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertJourneyStartRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertJourneyStart", Namespace="http://tempuri.org/", Order=0)]
        public TaxiDriverSystem.SQLWebServiceReference5.InsertJourneyStartRequestBody Body;
        
        public InsertJourneyStartRequest() {
        }
        
        public InsertJourneyStartRequest(TaxiDriverSystem.SQLWebServiceReference5.InsertJourneyStartRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertJourneyStartRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int DID;
        
        public InsertJourneyStartRequestBody() {
        }
        
        public InsertJourneyStartRequestBody(string date, int DID) {
            this.date = date;
            this.DID = DID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertJourneyStartResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertJourneyStartResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaxiDriverSystem.SQLWebServiceReference5.InsertJourneyStartResponseBody Body;
        
        public InsertJourneyStartResponse() {
        }
        
        public InsertJourneyStartResponse(TaxiDriverSystem.SQLWebServiceReference5.InsertJourneyStartResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertJourneyStartResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertJourneyStartResult;
        
        public InsertJourneyStartResponseBody() {
        }
        
        public InsertJourneyStartResponseBody(string InsertJourneyStartResult) {
            this.InsertJourneyStartResult = InsertJourneyStartResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertJourneyEndRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertJourneyEnd", Namespace="http://tempuri.org/", Order=0)]
        public TaxiDriverSystem.SQLWebServiceReference5.InsertJourneyEndRequestBody Body;
        
        public InsertJourneyEndRequest() {
        }
        
        public InsertJourneyEndRequest(TaxiDriverSystem.SQLWebServiceReference5.InsertJourneyEndRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertJourneyEndRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int DID;
        
        public InsertJourneyEndRequestBody() {
        }
        
        public InsertJourneyEndRequestBody(string date, int DID) {
            this.date = date;
            this.DID = DID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertJourneyEndResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertJourneyEndResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaxiDriverSystem.SQLWebServiceReference5.InsertJourneyEndResponseBody Body;
        
        public InsertJourneyEndResponse() {
        }
        
        public InsertJourneyEndResponse(TaxiDriverSystem.SQLWebServiceReference5.InsertJourneyEndResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertJourneyEndResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertJourneyEndResult;
        
        public InsertJourneyEndResponseBody() {
        }
        
        public InsertJourneyEndResponseBody(string InsertJourneyEndResult) {
            this.InsertJourneyEndResult = InsertJourneyEndResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JourneyIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JourneyID", Namespace="http://tempuri.org/", Order=0)]
        public TaxiDriverSystem.SQLWebServiceReference5.JourneyIDRequestBody Body;
        
        public JourneyIDRequest() {
        }
        
        public JourneyIDRequest(TaxiDriverSystem.SQLWebServiceReference5.JourneyIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class JourneyIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int D_ID;
        
        public JourneyIDRequestBody() {
        }
        
        public JourneyIDRequestBody(string date, int D_ID) {
            this.date = date;
            this.D_ID = D_ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JourneyIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JourneyIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaxiDriverSystem.SQLWebServiceReference5.JourneyIDResponseBody Body;
        
        public JourneyIDResponse() {
        }
        
        public JourneyIDResponse(TaxiDriverSystem.SQLWebServiceReference5.JourneyIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class JourneyIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int JourneyIDResult;
        
        public JourneyIDResponseBody() {
        }
        
        public JourneyIDResponseBody(int JourneyIDResult) {
            this.JourneyIDResult = JourneyIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class driverstartdaycheckRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="driverstartdaycheck", Namespace="http://tempuri.org/", Order=0)]
        public TaxiDriverSystem.SQLWebServiceReference5.driverstartdaycheckRequestBody Body;
        
        public driverstartdaycheckRequest() {
        }
        
        public driverstartdaycheckRequest(TaxiDriverSystem.SQLWebServiceReference5.driverstartdaycheckRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class driverstartdaycheckRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int D_ID;
        
        public driverstartdaycheckRequestBody() {
        }
        
        public driverstartdaycheckRequestBody(int D_ID) {
            this.D_ID = D_ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class driverstartdaycheckResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="driverstartdaycheckResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaxiDriverSystem.SQLWebServiceReference5.driverstartdaycheckResponseBody Body;
        
        public driverstartdaycheckResponse() {
        }
        
        public driverstartdaycheckResponse(TaxiDriverSystem.SQLWebServiceReference5.driverstartdaycheckResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class driverstartdaycheckResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string driverstartdaycheckResult;
        
        public driverstartdaycheckResponseBody() {
        }
        
        public driverstartdaycheckResponseBody(string driverstartdaycheckResult) {
            this.driverstartdaycheckResult = driverstartdaycheckResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class driverLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="driverLogin", Namespace="http://tempuri.org/", Order=0)]
        public TaxiDriverSystem.SQLWebServiceReference5.driverLoginRequestBody Body;
        
        public driverLoginRequest() {
        }
        
        public driverLoginRequest(TaxiDriverSystem.SQLWebServiceReference5.driverLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class driverLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public driverLoginRequestBody() {
        }
        
        public driverLoginRequestBody(string Username, string Password) {
            this.Username = Username;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class driverLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="driverLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaxiDriverSystem.SQLWebServiceReference5.driverLoginResponseBody Body;
        
        public driverLoginResponse() {
        }
        
        public driverLoginResponse(TaxiDriverSystem.SQLWebServiceReference5.driverLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class driverLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string driverLoginResult;
        
        public driverLoginResponseBody() {
        }
        
        public driverLoginResponseBody(string driverLoginResult) {
            this.driverLoginResult = driverLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DriverIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DriverID", Namespace="http://tempuri.org/", Order=0)]
        public TaxiDriverSystem.SQLWebServiceReference5.DriverIDRequestBody Body;
        
        public DriverIDRequest() {
        }
        
        public DriverIDRequest(TaxiDriverSystem.SQLWebServiceReference5.DriverIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DriverIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public DriverIDRequestBody() {
        }
        
        public DriverIDRequestBody(string Username, string Password) {
            this.Username = Username;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DriverIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DriverIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public TaxiDriverSystem.SQLWebServiceReference5.DriverIDResponseBody Body;
        
        public DriverIDResponse() {
        }
        
        public DriverIDResponse(TaxiDriverSystem.SQLWebServiceReference5.DriverIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DriverIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DriverIDResult;
        
        public DriverIDResponseBody() {
        }
        
        public DriverIDResponseBody(int DriverIDResult) {
            this.DriverIDResult = DriverIDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : TaxiDriverSystem.SQLWebServiceReference5.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<TaxiDriverSystem.SQLWebServiceReference5.WebService1Soap>, TaxiDriverSystem.SQLWebServiceReference5.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaxiDriverSystem.SQLWebServiceReference5.HelloWorldResponse TaxiDriverSystem.SQLWebServiceReference5.WebService1Soap.HelloWorld(TaxiDriverSystem.SQLWebServiceReference5.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            TaxiDriverSystem.SQLWebServiceReference5.HelloWorldRequest inValue = new TaxiDriverSystem.SQLWebServiceReference5.HelloWorldRequest();
            inValue.Body = new TaxiDriverSystem.SQLWebServiceReference5.HelloWorldRequestBody();
            TaxiDriverSystem.SQLWebServiceReference5.HelloWorldResponse retVal = ((TaxiDriverSystem.SQLWebServiceReference5.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference5.HelloWorldResponse> TaxiDriverSystem.SQLWebServiceReference5.WebService1Soap.HelloWorldAsync(TaxiDriverSystem.SQLWebServiceReference5.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference5.HelloWorldResponse> HelloWorldAsync() {
            TaxiDriverSystem.SQLWebServiceReference5.HelloWorldRequest inValue = new TaxiDriverSystem.SQLWebServiceReference5.HelloWorldRequest();
            inValue.Body = new TaxiDriverSystem.SQLWebServiceReference5.HelloWorldRequestBody();
            return ((TaxiDriverSystem.SQLWebServiceReference5.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaxiDriverSystem.SQLWebServiceReference5.InsertStartDayResponse TaxiDriverSystem.SQLWebServiceReference5.WebService1Soap.InsertStartDay(TaxiDriverSystem.SQLWebServiceReference5.InsertStartDayRequest request) {
            return base.Channel.InsertStartDay(request);
        }
        
        public string InsertStartDay(string date, int DID) {
            TaxiDriverSystem.SQLWebServiceReference5.InsertStartDayRequest inValue = new TaxiDriverSystem.SQLWebServiceReference5.InsertStartDayRequest();
            inValue.Body = new TaxiDriverSystem.SQLWebServiceReference5.InsertStartDayRequestBody();
            inValue.Body.date = date;
            inValue.Body.DID = DID;
            TaxiDriverSystem.SQLWebServiceReference5.InsertStartDayResponse retVal = ((TaxiDriverSystem.SQLWebServiceReference5.WebService1Soap)(this)).InsertStartDay(inValue);
            return retVal.Body.InsertStartDayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference5.InsertStartDayResponse> TaxiDriverSystem.SQLWebServiceReference5.WebService1Soap.InsertStartDayAsync(TaxiDriverSystem.SQLWebServiceReference5.InsertStartDayRequest request) {
            return base.Channel.InsertStartDayAsync(request);
        }
        
        public System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference5.InsertStartDayResponse> InsertStartDayAsync(string date, int DID) {
            TaxiDriverSystem.SQLWebServiceReference5.InsertStartDayRequest inValue = new TaxiDriverSystem.SQLWebServiceReference5.InsertStartDayRequest();
            inValue.Body = new TaxiDriverSystem.SQLWebServiceReference5.InsertStartDayRequestBody();
            inValue.Body.date = date;
            inValue.Body.DID = DID;
            return ((TaxiDriverSystem.SQLWebServiceReference5.WebService1Soap)(this)).InsertStartDayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaxiDriverSystem.SQLWebServiceReference5.InsertEndDayResponse TaxiDriverSystem.SQLWebServiceReference5.WebService1Soap.InsertEndDay(TaxiDriverSystem.SQLWebServiceReference5.InsertEndDayRequest request) {
            return base.Channel.InsertEndDay(request);
        }
        
        public string InsertEndDay(string date, int DID) {
            TaxiDriverSystem.SQLWebServiceReference5.InsertEndDayRequest inValue = new TaxiDriverSystem.SQLWebServiceReference5.InsertEndDayRequest();
            inValue.Body = new TaxiDriverSystem.SQLWebServiceReference5.InsertEndDayRequestBody();
            inValue.Body.date = date;
            inValue.Body.DID = DID;
            TaxiDriverSystem.SQLWebServiceReference5.InsertEndDayResponse retVal = ((TaxiDriverSystem.SQLWebServiceReference5.WebService1Soap)(this)).InsertEndDay(inValue);
            return retVal.Body.InsertEndDayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference5.InsertEndDayResponse> TaxiDriverSystem.SQLWebServiceReference5.WebService1Soap.InsertEndDayAsync(TaxiDriverSystem.SQLWebServiceReference5.InsertEndDayRequest request) {
            return base.Channel.InsertEndDayAsync(request);
        }
        
        public System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference5.InsertEndDayResponse> InsertEndDayAsync(string date, int DID) {
            TaxiDriverSystem.SQLWebServiceReference5.InsertEndDayRequest inValue = new TaxiDriverSystem.SQLWebServiceReference5.InsertEndDayRequest();
            inValue.Body = new TaxiDriverSystem.SQLWebServiceReference5.InsertEndDayRequestBody();
            inValue.Body.date = date;
            inValue.Body.DID = DID;
            return ((TaxiDriverSystem.SQLWebServiceReference5.WebService1Soap)(this)).InsertEndDayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaxiDriverSystem.SQLWebServiceReference5.InsertJourneyStartResponse TaxiDriverSystem.SQLWebServiceReference5.WebService1Soap.InsertJourneyStart(TaxiDriverSystem.SQLWebServiceReference5.InsertJourneyStartRequest request) {
            return base.Channel.InsertJourneyStart(request);
        }
        
        public string InsertJourneyStart(string date, int DID) {
            TaxiDriverSystem.SQLWebServiceReference5.InsertJourneyStartRequest inValue = new TaxiDriverSystem.SQLWebServiceReference5.InsertJourneyStartRequest();
            inValue.Body = new TaxiDriverSystem.SQLWebServiceReference5.InsertJourneyStartRequestBody();
            inValue.Body.date = date;
            inValue.Body.DID = DID;
            TaxiDriverSystem.SQLWebServiceReference5.InsertJourneyStartResponse retVal = ((TaxiDriverSystem.SQLWebServiceReference5.WebService1Soap)(this)).InsertJourneyStart(inValue);
            return retVal.Body.InsertJourneyStartResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference5.InsertJourneyStartResponse> TaxiDriverSystem.SQLWebServiceReference5.WebService1Soap.InsertJourneyStartAsync(TaxiDriverSystem.SQLWebServiceReference5.InsertJourneyStartRequest request) {
            return base.Channel.InsertJourneyStartAsync(request);
        }
        
        public System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference5.InsertJourneyStartResponse> InsertJourneyStartAsync(string date, int DID) {
            TaxiDriverSystem.SQLWebServiceReference5.InsertJourneyStartRequest inValue = new TaxiDriverSystem.SQLWebServiceReference5.InsertJourneyStartRequest();
            inValue.Body = new TaxiDriverSystem.SQLWebServiceReference5.InsertJourneyStartRequestBody();
            inValue.Body.date = date;
            inValue.Body.DID = DID;
            return ((TaxiDriverSystem.SQLWebServiceReference5.WebService1Soap)(this)).InsertJourneyStartAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaxiDriverSystem.SQLWebServiceReference5.InsertJourneyEndResponse TaxiDriverSystem.SQLWebServiceReference5.WebService1Soap.InsertJourneyEnd(TaxiDriverSystem.SQLWebServiceReference5.InsertJourneyEndRequest request) {
            return base.Channel.InsertJourneyEnd(request);
        }
        
        public string InsertJourneyEnd(string date, int DID) {
            TaxiDriverSystem.SQLWebServiceReference5.InsertJourneyEndRequest inValue = new TaxiDriverSystem.SQLWebServiceReference5.InsertJourneyEndRequest();
            inValue.Body = new TaxiDriverSystem.SQLWebServiceReference5.InsertJourneyEndRequestBody();
            inValue.Body.date = date;
            inValue.Body.DID = DID;
            TaxiDriverSystem.SQLWebServiceReference5.InsertJourneyEndResponse retVal = ((TaxiDriverSystem.SQLWebServiceReference5.WebService1Soap)(this)).InsertJourneyEnd(inValue);
            return retVal.Body.InsertJourneyEndResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference5.InsertJourneyEndResponse> TaxiDriverSystem.SQLWebServiceReference5.WebService1Soap.InsertJourneyEndAsync(TaxiDriverSystem.SQLWebServiceReference5.InsertJourneyEndRequest request) {
            return base.Channel.InsertJourneyEndAsync(request);
        }
        
        public System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference5.InsertJourneyEndResponse> InsertJourneyEndAsync(string date, int DID) {
            TaxiDriverSystem.SQLWebServiceReference5.InsertJourneyEndRequest inValue = new TaxiDriverSystem.SQLWebServiceReference5.InsertJourneyEndRequest();
            inValue.Body = new TaxiDriverSystem.SQLWebServiceReference5.InsertJourneyEndRequestBody();
            inValue.Body.date = date;
            inValue.Body.DID = DID;
            return ((TaxiDriverSystem.SQLWebServiceReference5.WebService1Soap)(this)).InsertJourneyEndAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaxiDriverSystem.SQLWebServiceReference5.JourneyIDResponse TaxiDriverSystem.SQLWebServiceReference5.WebService1Soap.JourneyID(TaxiDriverSystem.SQLWebServiceReference5.JourneyIDRequest request) {
            return base.Channel.JourneyID(request);
        }
        
        public int JourneyID(string date, int D_ID) {
            TaxiDriverSystem.SQLWebServiceReference5.JourneyIDRequest inValue = new TaxiDriverSystem.SQLWebServiceReference5.JourneyIDRequest();
            inValue.Body = new TaxiDriverSystem.SQLWebServiceReference5.JourneyIDRequestBody();
            inValue.Body.date = date;
            inValue.Body.D_ID = D_ID;
            TaxiDriverSystem.SQLWebServiceReference5.JourneyIDResponse retVal = ((TaxiDriverSystem.SQLWebServiceReference5.WebService1Soap)(this)).JourneyID(inValue);
            return retVal.Body.JourneyIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference5.JourneyIDResponse> TaxiDriverSystem.SQLWebServiceReference5.WebService1Soap.JourneyIDAsync(TaxiDriverSystem.SQLWebServiceReference5.JourneyIDRequest request) {
            return base.Channel.JourneyIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference5.JourneyIDResponse> JourneyIDAsync(string date, int D_ID) {
            TaxiDriverSystem.SQLWebServiceReference5.JourneyIDRequest inValue = new TaxiDriverSystem.SQLWebServiceReference5.JourneyIDRequest();
            inValue.Body = new TaxiDriverSystem.SQLWebServiceReference5.JourneyIDRequestBody();
            inValue.Body.date = date;
            inValue.Body.D_ID = D_ID;
            return ((TaxiDriverSystem.SQLWebServiceReference5.WebService1Soap)(this)).JourneyIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaxiDriverSystem.SQLWebServiceReference5.driverstartdaycheckResponse TaxiDriverSystem.SQLWebServiceReference5.WebService1Soap.driverstartdaycheck(TaxiDriverSystem.SQLWebServiceReference5.driverstartdaycheckRequest request) {
            return base.Channel.driverstartdaycheck(request);
        }
        
        public string driverstartdaycheck(int D_ID) {
            TaxiDriverSystem.SQLWebServiceReference5.driverstartdaycheckRequest inValue = new TaxiDriverSystem.SQLWebServiceReference5.driverstartdaycheckRequest();
            inValue.Body = new TaxiDriverSystem.SQLWebServiceReference5.driverstartdaycheckRequestBody();
            inValue.Body.D_ID = D_ID;
            TaxiDriverSystem.SQLWebServiceReference5.driverstartdaycheckResponse retVal = ((TaxiDriverSystem.SQLWebServiceReference5.WebService1Soap)(this)).driverstartdaycheck(inValue);
            return retVal.Body.driverstartdaycheckResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference5.driverstartdaycheckResponse> TaxiDriverSystem.SQLWebServiceReference5.WebService1Soap.driverstartdaycheckAsync(TaxiDriverSystem.SQLWebServiceReference5.driverstartdaycheckRequest request) {
            return base.Channel.driverstartdaycheckAsync(request);
        }
        
        public System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference5.driverstartdaycheckResponse> driverstartdaycheckAsync(int D_ID) {
            TaxiDriverSystem.SQLWebServiceReference5.driverstartdaycheckRequest inValue = new TaxiDriverSystem.SQLWebServiceReference5.driverstartdaycheckRequest();
            inValue.Body = new TaxiDriverSystem.SQLWebServiceReference5.driverstartdaycheckRequestBody();
            inValue.Body.D_ID = D_ID;
            return ((TaxiDriverSystem.SQLWebServiceReference5.WebService1Soap)(this)).driverstartdaycheckAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaxiDriverSystem.SQLWebServiceReference5.driverLoginResponse TaxiDriverSystem.SQLWebServiceReference5.WebService1Soap.driverLogin(TaxiDriverSystem.SQLWebServiceReference5.driverLoginRequest request) {
            return base.Channel.driverLogin(request);
        }
        
        public string driverLogin(string Username, string Password) {
            TaxiDriverSystem.SQLWebServiceReference5.driverLoginRequest inValue = new TaxiDriverSystem.SQLWebServiceReference5.driverLoginRequest();
            inValue.Body = new TaxiDriverSystem.SQLWebServiceReference5.driverLoginRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            TaxiDriverSystem.SQLWebServiceReference5.driverLoginResponse retVal = ((TaxiDriverSystem.SQLWebServiceReference5.WebService1Soap)(this)).driverLogin(inValue);
            return retVal.Body.driverLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference5.driverLoginResponse> TaxiDriverSystem.SQLWebServiceReference5.WebService1Soap.driverLoginAsync(TaxiDriverSystem.SQLWebServiceReference5.driverLoginRequest request) {
            return base.Channel.driverLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference5.driverLoginResponse> driverLoginAsync(string Username, string Password) {
            TaxiDriverSystem.SQLWebServiceReference5.driverLoginRequest inValue = new TaxiDriverSystem.SQLWebServiceReference5.driverLoginRequest();
            inValue.Body = new TaxiDriverSystem.SQLWebServiceReference5.driverLoginRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            return ((TaxiDriverSystem.SQLWebServiceReference5.WebService1Soap)(this)).driverLoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TaxiDriverSystem.SQLWebServiceReference5.DriverIDResponse TaxiDriverSystem.SQLWebServiceReference5.WebService1Soap.DriverID(TaxiDriverSystem.SQLWebServiceReference5.DriverIDRequest request) {
            return base.Channel.DriverID(request);
        }
        
        public int DriverID(string Username, string Password) {
            TaxiDriverSystem.SQLWebServiceReference5.DriverIDRequest inValue = new TaxiDriverSystem.SQLWebServiceReference5.DriverIDRequest();
            inValue.Body = new TaxiDriverSystem.SQLWebServiceReference5.DriverIDRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            TaxiDriverSystem.SQLWebServiceReference5.DriverIDResponse retVal = ((TaxiDriverSystem.SQLWebServiceReference5.WebService1Soap)(this)).DriverID(inValue);
            return retVal.Body.DriverIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference5.DriverIDResponse> TaxiDriverSystem.SQLWebServiceReference5.WebService1Soap.DriverIDAsync(TaxiDriverSystem.SQLWebServiceReference5.DriverIDRequest request) {
            return base.Channel.DriverIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<TaxiDriverSystem.SQLWebServiceReference5.DriverIDResponse> DriverIDAsync(string Username, string Password) {
            TaxiDriverSystem.SQLWebServiceReference5.DriverIDRequest inValue = new TaxiDriverSystem.SQLWebServiceReference5.DriverIDRequest();
            inValue.Body = new TaxiDriverSystem.SQLWebServiceReference5.DriverIDRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            return ((TaxiDriverSystem.SQLWebServiceReference5.WebService1Soap)(this)).DriverIDAsync(inValue);
        }
    }
}
